/**
 * Curated Binance USDT pairs — Markets, Trade quick-picks, and realtime ticks.
 * Generated from 24h quote volume (excludes stablecoins / leveraged tokens).
 * Regenerate: node scripts/write-trading-pairs.cjs
 */
export const TRADING_PAIRS_USDT = [
  'BTCUSDT',
  'ETHUSDT',
  'BNBUSDT',
  'SOLUSDT',
  'XRPUSDT',
  'DOGEUSDT',
  'ADAUSDT',
  'AVAXUSDT',
  'LINKUSDT',
  'DOTUSDT',
  'POLUSDT',
  'LTCUSDT',
  'ATOMUSDT',
  'APTUSDT',
  'ARBUSDT',
  'OPUSDT',
  'INJUSDT',
  'SUIUSDT',
  'PEPEUSDT',
  'SHIBUSDT',
  'TRXUSDT',
  'BCHUSDT',
  'FILUSDT',
  'ETCUSDT',
  'TONUSDT',
  'WLDUSDT',
  'SEIUSDT',
  'FETUSDT',
  'RENDERUSDT',
  'UNIUSDT',
  'ICPUSDT',
  'STXUSDT',
  'IMXUSDT',
  'GRTUSDT',
  'LDOUSDT',
  'AAVEUSDT',
  'MKRUSDT',
  'SANDUSDT',
  'MANAUSDT',
  'AXSUSDT',
  'XLMUSDT',
  'ALGOUSDT',
  'VETUSDT',
  'HBARUSDT',
  'EGLDUSDT',
  'SNXUSDT',
  'CRVUSDT',
  'RUNEUSDT',
  'KAVAUSDT',
  'ZECUSDT',
  'DASHUSDT',
  'CHZUSDT',
  'GALAUSDT',
  'APEUSDT',
  'GMTUSDT',
  '1INCHUSDT',
  'COMPUSDT',
  'CAKEUSDT',
  'XTZUSDT',
  'DYDXUSDT',
  'PENDLEUSDT',
  'JUPUSDT',
  'WIFUSDT',
  'ONDOUSDT',
  'ENSUSDT',
  'TIAUSDT',
  'ORDIUSDT',
  'CFXUSDT',
  'MINAUSDT',
  'ZRXUSDT',
  'LRCUSDT',
  'MASKUSDT',
  'API3USDT',
  'SSVUSDT',
  'MAGICUSDT',
  'ARUSDT',
  'JTOUSDT',
  'STRKUSDT',
  'ENAUSDT',
  'WUSDT',
  'TAOUSDT',
  'NOTUSDT',
  'ZKUSDT',
  'BBUSDT',
  'NEOUSDT',
  'KSMUSDT',
  'IOTAUSDT',
  'FLOWUSDT',
  'QNTUSDT',
  'ROSEUSDT',
  'ANKRUSDT',
  'STORJUSDT',
  'SUSHIUSDT',
  'THETAUSDT',
  'ENJUSDT',
  'BATUSDT',
  'HOTUSDT',
  'KNCUSDT',
  'CELOUSDT',
  'ONEUSDT',
  'ICXUSDT',
  'ONTUSDT',
  'QTUMUSDT',
  'ZENUSDT',
  'SFPUSDT',
  'BELUSDT',
  'COTIUSDT',
  'CHRUSDT',
  'SKLUSDT',
  'PEOPLEUSDT',
  'AUDIOUSDT',
  'ACHUSDT',
  'FXSUSDT',
  'RPLUSDT',
  'CYBERUSDT',
  'MANTAUSDT',
  'PIXELUSDT',
  'PORTALUSDT',
  'AXLUSDT'
];

export const TRADING_PAIRS_SET = new Set(TRADING_PAIRS_USDT);

/** Hidden from Markets list and search */
export const MARKETS_EXCLUDED_PAIRS = new Set(['NEARUSDT', 'MORPHOUSDT']);

/** Default when no symbol in URL */
export const DEFAULT_TRADE_SYMBOL = 'BTCUSDT';

export const MARKETS_DEFAULT_LIMIT = 120;
export const MARKETS_SEARCH_LIMIT = 200;
